apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      scale:
        disabled: true
      source:
        generator:
          # How many messages to generate in the duration.
          rpu: 10
          duration: 10s
          # Optional, size of each generated message, defaults to 10.
          msgSize: 10
    - name: even-or-odd-flatmap
      metadata:
        annotations:
          # numaflow.numaproj.io/map-stream: "true"
          numaflow.numaproj.io/flat-map: "true"
      limits:
        # Keeps batched result under 1MB
        readBatchSize: 30
      scale:
        disabled: true
      # limits:
      #   readBatchSize: 1
      udf:
        container:
          imagePullPolicy: Never
          image: "quay.io/numaio/numaflow-python/flatmap:stable"
          args:
          - python
          - example_flatmap.py
          - flatmap
          env:
          - name: MAX_THREADS
            value: "1"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: SLEEP_TIME_SEC
            value: "0"
          resources: &resources
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
      containerTemplate:
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
            
###
    - name: even-or-odd-batch
      metadata:
        annotations:
          # numaflow.numaproj.io/map-stream: "true"
          numaflow.numaproj.io/flat-map: "true"
      limits:
        # Keeps batched result under 1MB
        readBatchSize: 30
      scale:
        disabled: true
      # limits:
      #   readBatchSize: 1
      udf:
        container:
          imagePullPolicy: Never
          image: "quay.io/numaio/numaflow-python/flatmap:stable"
          args:
          - python
          - example_flatmap.py
          - batch
          env:
          - name: MAX_THREADS
            value: "1"
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: SLEEP_TIME_SEC
            value: "0"
          resources: &resources
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
      containerTemplate:
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
###

    - name: even-sink
      scale:
        min: 1
      sink:
        # A simple log printing sink
        log: {}
    - name: odd-sink
      scale:
        min: 1
      sink:
        log: {}
    - name: number-sink
      scale:
        min: 1
      sink:
        log: {}
      
  edges:
    - from: in
      to: even-or-odd-flatmap
    - from: even-or-odd-flatmap
      to: even-sink
      conditions:
        tags:
          values:
            - even-tag
    - from: even-or-odd-flatmap
      to: odd-sink
      conditions:
        tags:
          operator: or
          values:
            - odd-tag
    - from: even-or-odd-flatmap
      to: number-sink
      conditions:
        tags:
          values:
            - grouped

    - from: in
      to: even-or-odd-batch
    - from: even-or-odd-batch
      to: even-sink
      conditions:
        tags:
          values:
            - even-tag
    - from: even-or-odd-batch
      to: odd-sink
      conditions:
        tags:
          operator: or
          values:
            - odd-tag
    - from: even-or-odd-batch
      to: number-sink
      conditions:
        tags:
          values:
            - grouped