# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapbatch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emapbatch.proto\x12\x0bmapbatch.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x01\n\nMapRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12.\n\nevent_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\twatermark\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x07headers\x18\x05 \x03(\x0b\x32$.mapbatch.v1.MapRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\x0fMapBatchRequest\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.mapbatch.v1.MapRequest\"~\n\x10MapBatchResponse\x12\x35\n\x07results\x18\x01 \x03(\x0b\x32$.mapbatch.v1.MapBatchResponse.Result\x1a\x33\n\x06Result\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0c\n\x04tags\x18\x03 \x03(\t\"\x1e\n\rReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\x94\x01\n\x08MapBatch\x12I\n\nMapBatchFn\x12\x1c.mapbatch.v1.MapBatchRequest\x1a\x1d.mapbatch.v1.MapBatchResponse\x12=\n\x07IsReady\x12\x16.google.protobuf.Empty\x1a\x1a.mapbatch.v1.ReadyResponseB<Z:github.com/numaproj/numaflow-go/pkg/apis/proto/mapbatch/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapbatch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z:github.com/numaproj/numaflow-go/pkg/apis/proto/mapbatch/v1'
  _MAPREQUEST_HEADERSENTRY._options = None
  _MAPREQUEST_HEADERSENTRY._serialized_options = b'8\001'
  _globals['_MAPREQUEST']._serialized_start=94
  _globals['_MAPREQUEST']._serialized_end=333
  _globals['_MAPREQUEST_HEADERSENTRY']._serialized_start=287
  _globals['_MAPREQUEST_HEADERSENTRY']._serialized_end=333
  _globals['_MAPBATCHREQUEST']._serialized_start=335
  _globals['_MAPBATCHREQUEST']._serialized_end=395
  _globals['_MAPBATCHRESPONSE']._serialized_start=397
  _globals['_MAPBATCHRESPONSE']._serialized_end=523
  _globals['_MAPBATCHRESPONSE_RESULT']._serialized_start=472
  _globals['_MAPBATCHRESPONSE_RESULT']._serialized_end=523
  _globals['_READYRESPONSE']._serialized_start=525
  _globals['_READYRESPONSE']._serialized_end=555
  _globals['_MAPBATCH']._serialized_start=558
  _globals['_MAPBATCH']._serialized_end=706
# @@protoc_insertion_point(module_scope)
